### PR TITLE
Additional GC methods

### LINKED ISSUE #77: Implement GC features
I'd like to make the GC more accessible from the Rust side.

### PR DESCRIPTION
**Pull request by danielpclark**
Closes #77

### CODE REVIEW

**Comment by irxground** [comment]
If it is not my misunderstanding, the range marked with `rb_gc_mark_locations` is`start <= x < end`. Therefore, the following code does not seem to mark the last element.

```rust
let arr = [
    RString::new_utf8("1"),
    RString::new_utf8("2"),
    RString::new_utf8("3"),
    RString::new_utf8("4"),
];
GC::mark_locations(&arr[0], &arr[3]);
```

I think that `binding::gc::mark_locations` is dangerous unless it has the following signature.

```rust
pub fn mark_locations(range: &[Value])
```

But if you do so it may not work well with `class::GC::mark_locations`

**Comment by danielpclark** [comment]
> But if you do so it may not work well with `class::GC::mark_locations`

It's only on master and an official version hasn't been released so it's okay to change it.

> Therefore, the following code does not seem to mark the last element.

I'll look into this shortly…

**Comment by danielpclark** [comment]
Given

```ruby
["1", "2", "3", "4"]
```

With RValue memory widths of 40 bytes each.  If the memory ptr for the first one was at location 1000, then the second one would be 1040, the third 1080, and the fourth 1120.

```C
static void
gc_mark_locations(rb_objspace_t *objspace, const VALUE *start, const VALUE *end)
{
    long n;

    if (end <= start) return; /* if 1120 <= 1000 */
    n = end - start; /* 1120 - 1000 = 4 // 4 RValues of 40 bytes */
    mark_locations_array(objspace, start, n); /* objspace, 1000, 4 */
}
```

```C
mark_locations_array(rb_objspace_t *objspace, register const VALUE *x, register long n)
// First iteration
{ 
    VALUE v;
    while (n--) { /* (4) - 1 */
        v = *x; /* Value from address at 1000 */
        gc_mark_maybe(objspace, v); /* mark it */
        x++; /* Next Value at 1040 */
    }
}
// Second iteration
{
    VALUE v;
    while (n--) { /* (3) - 1 */
        v = *x; /* Value from address at 1040 */
        gc_mark_maybe(objspace, v);  /* mark it */
        x++;  /* Next Value at 1080 */
    }
}
// Third iteration
{
    VALUE v;
    while (n--) { /* (2) - 1 */
        v = *x; /* Value from address at 1080 */
        gc_mark_maybe(objspace, v);  /* mark it */
        x++;  /* Next Value at 1120 */
    }
}
// Fourth iteration
{
    VALUE v;
    while (n--) { /* (1) - 1 */
        v = *x; /* Value from address at 1120 */
        gc_mark_maybe(objspace, v);  /* mark it */
        x++;  /* Next Value at 1160 */
    }
}
// Fifth iteration
{
    VALUE v;
    while (n--) { /* (0)  // EXIT LOOP */
        v = *x;
        gc_mark_maybe(objspace, v);
        x++;
    }
}
```

Correct me if my math is wrong but it does **“seem to mark the last element”**.

As for `mark_locations(range: &[Value])` I'm more than happy to make this change now.

**Comment by danielpclark** [comment]
Ah… Maybe my math is wrong here.  It depends on this:

    n = end - start; /* 1120 - 1000 = 4 // 4 RValues of 40 bytes */

Which could be 3 if C starts its count at 0... Looking into it.  Yes this is basic understanding in C but I'm not yet a C programmer.

**Comment by irxground** [comment]
The reason I thought that the current code is wrong is because of the following code.
```c
if (end <= start) return;
```
According to this code, it does nothing when `start == end`. So referring to the current `GC::mark_locations` example, it does not do anything when the array length is 1.

**Comment by danielpclark** [comment]
I just implemented `GC::is_marked` and tested it against the `GC::mark_locations` result and it has only marked the first item in the array and none of the other ones.  I'm debugging it now.

**Comment by danielpclark** [comment]
Thinking about it plainly I can simply iterate over all the items in range and call the mark_maybe function on it straight from Rust.  I don't need to use the `rb_gc_mark_locations` directly since I can simply rewrite it here.

**Pull request merged**
