### PR TITLE
Fix segfaults caused by closures passed to `Thread` methods

### LINKED ISSUE #69: Thread::call_with_gvl causes pointer being freed was not allocated
Hi,

I am using `rutie` to create a ruby gem for a rust library that basically fetches units of work from a server and then calls ruby classes to process those units. To make concurrent I am using `Thread::call_without_gvl` to release the GVL while doing network operations in rust and then `Thread::call_with_gvl` to make ruby calls. I could probably restructure the code to avoid the `call_with_gvl` call, but the `'static` requirement for the closures makes it a bit tricky.

When calling the method below from ruby it fails with
```
ruby(9818,0x117bcb5c0) malloc: *** error for object 0x7fa850ef40a0: pointer being freed was not allocated
ruby(9818,0x117bcb5c0) malloc: *** set a breakpoint in malloc_error_break to debug
```
The weird thing is that the rust test works without issues.

<details><summary>Rust source</summary>

```rust
#[macro_use]
extern crate rutie;

use rutie::{Class, Object, RString, Thread, VM};

class!(RutieExample);

methods!(
    RutieExample,
    _itself,
    fn work(_input: RString) -> RString {
        let worker_class = "Object".to_string();
        let b = Thread::call_without_gvl(
            move || {
                // Releasing the GVL here to do network IO
                // After we fetched a unit of work I wanto to call a ruby object
                Thread::call_with_gvl(move || {
                    // Uncommenting this line "fixes" the issue
                    // let worker_class = "Object".to_string();
                    let ruby_worker = Class::from_existing(&worker_class);
                    ruby_worker.send("name", None)
                })
            },
            Some(|| {}),
        );

        match b.try_convert_to::<RString>() {
            Ok(ruby_string) => ruby_string,
            Err(_) => RString::new_utf8("Fail!"),
        }
    }
);

#[allow(non_snake_case)]
#[no_mangle]
pub extern "C" fn Init_rutie_ruby_example() {
    Class::new("RutieExample", None).define(|itself| {
        itself.def_self("work", work);
    });
}

#[test]
fn it_works() {
    // Rust projects must start the Ruby VM
    VM::init();

    Init_rutie_ruby_example();

    let ruby_worker = Class::from_existing("RutieExample");
    let res = ruby_worker.send("work", None);

    let res = match res.try_convert_to::<RString>() {
        Ok(ruby_string) => ruby_string,
        Err(_) => RString::new_utf8("Fail!"),
    };
    assert_eq!("Object", &res.to_string());
}

```

</details>

<details><summary>lldb stack strace</summary>

```(lldb) target create ~/.rbenv/versions/2.5.3/bin/ruby
Current executable set to '~/.rbenv/versions/2.5.3/bin/ruby' (x86_64).
(lldb) breakpoint set --name malloc_error_break
Breakpoint 1: where = libsystem_malloc.dylib`malloc_error_break, address = 0x00000000000170de
(lldb) run -Ilib fail.rb
Process 8370 launched: '/Users/dominik/.rbenv/versions/2.5.3/bin/ruby' (x86_64)
ruby(8370,0x1000b95c0) malloc: *** error for object 0x10070d790: pointer being freed was not allocated
ruby(8370,0x1000b95c0) malloc: *** set a breakpoint in malloc_error_break to debug
Process 8370 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00007fff5e9a00de libsystem_malloc.dylib`malloc_error_break
libsystem_malloc.dylib`malloc_error_break:
->  0x7fff5e9a00de <+0>: pushq  %rbp
    0x7fff5e9a00df <+1>: movq   %rsp, %rbp
    0x7fff5e9a00e2 <+4>: nop
    0x7fff5e9a00e3 <+5>: nopl   (%rax)
Target 0: (ruby) stopped.
(lldb) up
frame #1: 0x00007fff5e993676 libsystem_malloc.dylib`malloc_vreport + 437
libsystem_malloc.dylib`malloc_vreport:
    0x7fff5e993676 <+437>: cmpb   $0x1, 0x32c47d6f(%rip)    ; debug_mode + 3
    0x7fff5e99367d <+444>: jne    0x7fff5e9936a3            ; <+482>
    0x7fff5e99367f <+446>: leaq   0x18458(%rip), %rsi       ; "*** sending SIGSTOP to help debug\n"
    0x7fff5e993686 <+453>: movl   $0x5, %edi
(lldb) up
frame #2: 0x00007fff5e9934a3 libsystem_malloc.dylib`malloc_report + 152
libsystem_malloc.dylib`malloc_report:
    0x7fff5e9934a3 <+152>: movq   0x32c45b66(%rip), %rax    ; (void *)0x00007fff915c6070: __stack_chk_guard
    0x7fff5e9934aa <+159>: movq   (%rax), %rax
    0x7fff5e9934ad <+162>: cmpq   -0x8(%rbp), %rax
    0x7fff5e9934b1 <+166>: jne    0x7fff5e9934bc            ; <+177>
(lldb) up
frame #3: 0x000000010194709a librutie_ruby_example.dylib`alloc::alloc::dealloc::hef07b11e979696ba(ptr="", layout=Layout @ 0x00007ffeefbfeb40) at alloc.rs:96
(lldb) up
frame #4: 0x00000001019470f9 librutie_ruby_example.dylib`alloc::alloc::box_free::h1a8734277b8c0de7(ptr=Unique<rutie::class::any_object::AnyObject> @ 0x00007ffeefbfeb60) at alloc.rs:206
(lldb) up
frame #5: 0x00000001019464ad librutie_ruby_example.dylib`rutie::util::ptr_to_data::h4762f8239518f213(ptr=0x000000010070d790) at util.rs:101
   98
   99  	pub unsafe fn ptr_to_data<R>(ptr: *mut c_void) -> R {
   100 	    *Box::from_raw(ptr as *mut R)
-> 101 	}
(lldb) up
frame #6: 0x000000010194715c librutie_ruby_example.dylib`rutie::binding::thread::call_with_gvl::hbebc4468eca2e309(func=<unavailable>) at thread.rs:92
   89  	            util::closure_to_ptr(func),
   90  	        );
   91
-> 92  	        util::ptr_to_data(ptr)
   93  	    }
   94  	}
   95
(lldb) up
frame #7: 0x0000000101946c08 librutie_ruby_example.dylib`rutie::class::thread::Thread::call_with_gvl::h24af48b7283f4583(func=<unavailable>) at thread.rs:138
   135 	    where
   136 	        F: 'static + FnOnce() -> R,
   137 	    {
-> 138 	        thread::call_with_gvl(func)
   139 	    }
   140 	}
   141
(lldb) up
frame #8: 0x0000000101946458 librutie_ruby_example.dylib`rutie_ruby_example::work::_$u7b$$u7b$closure$u7d$$u7d$::h3a14ca771a91723e at lib.rs:17
   14  	            move || {
   15  	                // Releasing the GVL here to do network IO
   16  	                // After we fetched a unit of work I wanto to call a ruby object
-> 17  	                Thread::call_with_gvl(move || {
   18  	                    // Uncommenting this line "fixes" the issue
   19  	                    // let worker_class = "Object".to_string();
   20  	                    let ruby_worker = Class::from_existing(&worker_class);
(lldb)
```

</details>

### PR DESCRIPTION
**Pull request by dsander**
I sadly still don't _really_ understand how the changes work, but did my best explaining my though process, which I hope makes sense 😄 

---------------------------------

Fix segfaults when calling Thread::call_without_gvl and call_with_gvl

I can't really explain why requiring `FnMut` over `FnOnce` fixes the
problems described in #69. I only discovered that all examples for
passing closure to C callbacks were using `FnMut` and not `FnOnce`.
Based on the stacktraces I saw I am assuming that the compiler captures
and returns the variables differently which somehow extends(?) their
lifetime.

Moving the `func` into the `wrap_return` seems to be required to ensure
the return value lives long enough.

Due to the additional requirements of `FnMut` the `'static` lifetime of
the closures are not required anymore. They have been introduced to fix
[this issue][1]. The original example now also does not compile and
requires `str` to be cloned. Done that it compiles and runs without a
segfault.

[1]: https://github.com/d-unseductable/ruru/issues/64

-------------------------------------------

Fix creating Thread::new when passing a closure capturing variables

Without requiring `FnMut` closures creating a ruby thread using a
closure capturing variables segfaulted.

Fixes #69

### CODE REVIEW

**Comment by irxground** [comment]
The reason why the previous code does not work as expected seems to be a mistake of type.

`binding::thread::call_without_gvl` receives `FnOnce` as an argument.
https://github.com/danielpclark/rutie/blob/60d22b206cfd7afff26e2df4f640479e5a391071/src/binding/thread.rs#L30-L32

However, `thread_call_callbox` is passed to `rb_thread_call_without_gvl`, and this callback function assumes `FnMut`.
https://github.com/danielpclark/rutie/blob/60d22b206cfd7afff26e2df4f640479e5a391071/src/binding/thread.rs#L106-L107

This pull request modifies the type, so it will be working properly

**Comment by danielpclark** [comment]
@irxground Thanks!  I really appreciate it. :+1:

**Comment by danielpclark** [comment]
Thanks @irxground .

I believe this PR is also following `b)` to avoid a premature `free`, from either Ruby or Rust, of memory that was still in use.  So that's good and I appreciate you clarifying it.

---

As far as `c) Resources created inside functions` being a cause for `c) Both functions leak memory` I do think that this depends on which side of things a particular program is implemented towards (**ie:** a Ruby program using Rust **vs** a Rust program using Ruby).  _These are just my thoughts and I haven't proven it though._

If the program is a **Rust extension to a Ruby program** then I think resources created inside functions will be handled properly as Ruby has overall ownership of it.

As for **Rust programs that integrate Ruby** I think that may be more of a issue… and perhaps having a Rust wrapper object in Ruby be the resource creator from which the Ruby side needs to instantiate it.  In other words create a custom struct wrapper object in Rust for Ruby to create with as a return type.  This way when Ruby instantiates that object with input the ownership of what was created will reside within Rust.  _Also I haven't yet used wrapper struct objects from Rust in Ruby yet myself so I don't know from experience the benefits or disadvantages._

But I don't think that that's an issue this PR needs to be concerned with. :+1:

**Comment by dsander** [comment]
Thank you both!

**Comment by danielpclark** [comment]
No, thank you. :smiley:

**Pull request merged**
