### PR TITLE
Remove Option wrapper around arguments that are passed to ruby functions

### PR DESCRIPTION
**Pull request by dsander**
Remove Option wrapper around arguments that are passed to ruby functions

Instead of passing `None` use `&[]` when no arguments are needed.

~~Since is it not possible to dynamically allocate a slice, we should
allow to pass vectors as arguments that are used to call ruby functions.~~

~~This allows to dynamically define the arguments in rust as vectors.~~

~~Due to the generic type calling those functions with no arguments (`None`)
requires to define the type for `T` even though it is not used.~~

@danielpclark What do you think about changing the signatures to this?
```rust
fn send<T>(&self, method: &str, arguments: &T) -> AnyObject
    where
        T: AsRef<[AnyObject]>
```

I think `object.send("method", &[])` would write and read nicer than `object.send::<&[AnyObject]>("method", None)`

### CODE REVIEW

**Comment by danielpclark** [comment]
I like the idea.  It may have the same issue I was trying to get by here though: [is-support-for-impl-trait-coming-to-allow-use-of-empty-slice](https://users.rust-lang.org/t/is-support-for-impl-trait-coming-to-allow-use-of-empty-slice/19716).  And the problem is relating to sizes not being known at compile time.  As you can see from the CI test in the thread example it fails for this same reason.

**Comment by danielpclark** [comment]
> Since is it not possible to dynamically allocate a slice

Forgive me but does this not work dynamically? https://doc.rust-lang.org/std/vec/struct.Vec.html#method.as_slice

**Comment by dsander** [comment]
> And the problem is relating to sizes not being known at compile time. As you can see from the CI test in the thread example it fails for this same reason.

I don't think we would have that problem here, `T` is either `Vec` or `[]` and the compiler needs to know know which implementation should be called. Passing `&[]` should allow it to determine that `T` is `[]`. 

In your case the generic type is the content of the slice, passing in an empty slice does not allow the compiler to infer the concrete implementation.


> Forgive me but does this not work dynamically? https://doc.rust-lang.org/std/vec/struct.Vec.html#method.as_slice

You are right, my problem was that I could not figure out how to get from a `Option<Vec<AnyObject>` to `Option<&[AnyObject]>`, turns out `option.as_ref().map(Vec::as_slice)` works just fine. 🤦‍♂️ Thanks for pointing me to that method!


If you agree that passing an empty slice instead of `None` would be the nicer API I will open another PR.

**Comment by danielpclark** [comment]
Yes I do think it would be nicer.  If you're able to get it to work without any complaints for known size at compile time then go for it.  I do think your `AsRef` feature is still a really nice idea.  Just like methods that can accept either `String` or `&str` I'm still in favor of a feature like this... removing `Option` would be a bonus.

**Comment by dsander** [comment]
>  I do think your `AsRef` feature is still a really nice idea. Just like methods that can accept either `String` or `&str` I'm still in favor of a feature like this... removing `Option` would be a bonus.

Sounds good to me, I'll keep working on it in this PR then.

> However the implementation is implemented I believe we still want to use stack rather than heap.

That makes sene, no need to allocate a Vec if we don't have to.

**Comment by dsander** [comment]
I skimmed through the docs and example and I think those four occurrences need to be updated after merging this:

```
examples/rutie_rust_example/src/main.rs
9:    let b = a.send("reverse", None);

src/class/vm.rs
518:    /// fn protect_send(&self, method: &str, arguments: Option<&[AnyObject]>) -> Result<AnyObject, AnyException> {
545:    /// fn protect_send(&self, method: &str, arguments: Option<&[AnyObject]>) -> Result<AnyObject, AnyException> {
569:    /// fn protect_send(&self, method: &str, arguments: Option<&[AnyObject]>) -> Result<AnyObject, AnyException> {
```

**Comment by danielpclark** [comment]
This one would be good.

I'm trying to think how we might test this against https://github.com/danielpclark/rutie#segfault-during-gc-when-using-a-ruby-method-written-in-c

In the event I discovered the issue it was during a benchmark that would test querying a directory tens of thousands of times and  only during that high volume would GC hit and cause a segfault.  This is why we have been avoiding vecs for holding Ruby objects since the GC doesn't handle heap memory well.

Is it possible to change the return type of `util::arguments_to_values` to `&[Value]` ?  I'm thinking it's not, but in the contexts where `util::arguments_to_values` is used perhaps we could at least call `.as_slice` on the result.  Internally I'd like to avoid passing anything to Ruby's C code which is stored as a `Vec`.  I'm fine with users of Rutie using `Vec` so long as we can make it safe by changing to a slice.

AsRef does allow for `Vec[]` to `&[]` so maybe it would be that simple to do.

**Comment by danielpclark** [comment]
> > but in the contexts where util::arguments_to_values is used perhaps we could at least call .as_slice on the result.

> Would that make a difference? I would assume the pointer passed to C still points at the same memory location.

Honestly I don't know.  From reading this signature:

```rust
/// Extracts a slice containing the entire vector.
pub fn as_slice(&self) -> &[T] {
    self
}
```

I had thought that might be enough.  But reading:

```rust
/// `Vec` will never perform a "small optimization" where elements are actually
/// stored on the stack for two reasons…
```

I guess it's not the same thing.

> Do you have a somehow reproduce able test for the issue?

Yes and no.  I can tell you how it was done exactly.  Basically in my gem [faster_path](https://github.com/danielpclark/faster_path) I had implemented the `#entries` method which gets the entries for the current directory.  It starts by creating a bunch of `Pathname` instances from the Rust side, exactly as described in the link I gave you earlier, and benchmarked maybe generating 10 thousand to 20 thousand instances of Pathname causing GC to trigger during the process.  If you look closely at the README section there are two things that changed, not just one, one being switching from heap to stack as prescribed.  But the other, which may also be a reason that may have fixed it, is assigning the parameter with `let` before the method call so the scope of the lifetime of the object in Rust should be broader than the `vec` instantiated within the parameter block.

I was simply following advice here and seeing as how it fixed the problem I believed what was said was likely true.

Looking at the `IntoIter` implementation on `Vec` I see that the vec is still data held in contiguous memory from `slice::from_raw_parts(self.ptr, self.len())` so I wouldn't think the GC should have issue from that.  I would have to look more in to it.

> Do we know definitely know that the ruby GC is causing the segfault?

Yes and no.  We know it happens during GC but “I” don't know for sure the cause.

> I would need to read up on the GC internals, but how can it start from the stack, isn't everything in ruby dynamic and thus must be stored on the heap?

This is the first I've started looking in to that myself since you asked.  And from a quick look from online resources it would seem Ruby objects are stored on the heap, but Fibers are stored on the stack. … Yeas further looking it seems everything says Ruby uses the heap.  So :man_shrugging: .

> Do you have a somehow reproduce able test for the issue?

I think a good test would be to instantiate 20,000 instances of `Pathname` in Rust and call a GC clean action.  `Pathname` is written in C in Ruby which makes implementing stuff for it in Rust a little more on the dangerous side.  Not hard, but occasionally you need to do more to get it right.

> If either side is freeing memory do we maybe need to `mem::free`/`Box::leak` it or mark it in the ruby VM so that we can take care of it in rust?

I think you are right when you said the word **mark**.  If we can reproduce this problem I think the solution will be to use `rb_gc_mark` and then have the Rust `Drop` feature perhaps handle it when we're done.  That in itself would take some research and maybe some trial and error.

Of course if the hole issue was simply because I didn't have the scope of the variable as broad as it should have been by having the `let` for the arguments outside of the command call itself then this is simply worrying over nothing.

**Comment by danielpclark** [comment]
We could put a note on the methods that using an array for parameters rather than a `Vec` may be a safer bet.  And then we can learn over time if it is indeed an issue just from the feedback we get.  What do you think?

**Comment by danielpclark** [comment]
This may be related https://github.com/tildeio/helix/issues/50 and perhaps we can glean some info from there.

**Comment by danielpclark** [comment]
I'll work on reproducing the issue.  Feel free to do so as well.

**Comment by dsander** [comment]
I wasn't able to recreate the segfault using the code in `faster_path` (even the old version of your example worked), however recreating it using similar calls nokogiri does worked: https://github.com/dsander/rutie/commit/f0a6a98a608bc600067e90a3cb367d1c2734d6e7

This reproducibly segfaults after printing out a few of the arguments. Disabling the GC fixes the problem, so I think you are right and we have to do something about those ruby object we allocate.

I don't think this is directly related to this MR as it is reproduce able in the master branch, passing in a `Vec` already works if it's done in a specific way. I'll check that tomorrow but think we don't need the whole `AsRef` shebang without wrapping `Option`.

**Comment by danielpclark** [comment]
So I found the original issue in FasterPath: https://github.com/danielpclark/rutie/issues/3

**Comment by danielpclark** [comment]
> possible to dynamically allocate

I was thinking about this.  And I just remembered you can use `rutie::Array` just as you would a vector.  You may even do something like `let result: Array = ...collect();`  And collect will return the Rutie `Array` type full of Ruby objects.

**Comment by dsander** [comment]
> What are you saying here? No to `AsRef`? Yes to `AsRef` and no to `Option`? Wrapping `Option`?

I mean is that with the removal of the `Option` we don't need the `where T: AsRef` bound because `Vec` already implements `impl<T> AsRef<[T]> for Vec<T>`. If you plan to implement `AsRef<[AnyObject]>` for any other `rutie` struct it might make sense to keep it, otherwise we can simply use `fn send(&self, method: &str, arguments: &[AnyObject]) -> AnyObject`


> I was thinking about this. And I just remembered you can use `rutie::Array` just as you would a vector. You may even do something like `let result: Array = ...collect();` And collect will return the Rutie `Array` type full of Ruby objects.

Are you thinking about allowing or requiring `Array`s to be passed the `Object#send` and similar methods?



> Thinking about the width of space a Vector uses I'm not sure it packs them together in quite the same way. When the GC then goes to free the objects in the vector **likely** given merely the start pointer and the length then what's it going to do when it's not aligned the same as the memory it's designed to handle?

I think the GC is freeing `Value` from the `Vec` we create in Rust in this [loop](https://github.com/dsander/rutie/commit/f0a6a98a608bc600067e90a3cb367d1c2734d6e7#diff-d1a31e5159f1939ef6a06e27685aef5fR5). It would surprise me if the GC would mess with non Value objects on the heap, but maybe those free calls mess up the structure of the Vec in memory? 

> If your struct contains a pointer to a C array of `VALUE`s, you can instead use `rb_gc_mark_locations()` which takes two arguments: the pointers to the start and end of the array (the end being equal to the starting pointer plus the array length).

That looks like a nice improvement over [`rb_gc_register_address`](https://github.com/sparklemotion/nokogiri/commit/0a1556a7c0ac1dc58c074a06f639bba3ddabab3f)

**Comment by danielpclark** [comment]
> > I was thinking about this. And I just remembered you can use rutie::Array just as you would a vector. You may even do something like let result: Array = ...collect(); And collect will return the Rutie Array type full of Ruby objects.

> Are you thinking about allowing or requiring Arrays to be passed the Object#send and similar methods?

No.  Eventually I'd like to be able to support splat like behavior for Arrays.  See #8 .  That aside...

Method calls both from Ruby, and to Ruby, use parameters as `argc: Argc, argv: *const AnyObject` which is defined in both the DSL `method!` macro `let _arguments = $crate::util::parse_arguments(argc, argv);` and the `send` method uses `rutie::binding::vm::call_method` internally which does `let (argc, argv) = util::process_arguments(arguments);`.  So no matter which way we communicate arguments we need to simply convert it to this format which is already implemented.

Now I get what your asking where send could take `Array` instead of, or in conjunction to `&[]` rather than `&[array.into()]` as having a Ruby array as the first parameter is not the same as passing many arguments as if a splat operator were used on it.  I'm thinking perhaps we could implement out our own `Into` trait for both `&[AnyObject]` and `Array` to cast out as an `(Argc, Argv)` kind of output and use that particular `Into` trait as the `send` method parameter requirement.  Of course I want this trait to be only available internally on the `binding` layer but I think that something like this may be possible.

Eventually when we get to adding splat operator behavior support in the DSL we'll need to implement something like prepending existing arguments for the method into the `Array` object before casting it to the `Argc, Argv` we use.

I'm using the term `casting` lightly here as this is no primitive cast.

**Comment by danielpclark** [comment]
You know, I've gotten so used to Vec's just having this issue that I hadn't considered that that could be fixed.  But since https://github.com/danielpclark/rutie/issues/21#issuecomment-455398629 I now am thinking that perhaps it is possible.  Mainly because I'm open to considering it now more than before.

**Comment by dsander** [comment]
> I'm thinking perhaps we could implement out our own `Into` trait for both `&[AnyObject]` and `Array` to cast out as an `(Argc, Argv)` kind of output and use that particular `Into` trait as the `send` method parameter requirement.

Right, I was thinking of implementing `AsRef<[AnyObject]>` for `Array`, but since I am not sure if that would work I removed the `AsRef` code for now. 

This PR now just removes the `Option` around the arguments which makes it easier to pass in vectors. If you are ok with the changes I will squash the commits and update the PR description.

> but I had mistakenly assumed that the `as_slice` method made everything okay.


That would have been nice though 😄 I tried a [few things to fix the segfault](https://github.com/dsander/rutie/blob/fed4275fac200603cb66232465deacacddb59294/examples/rutie_ruby_gvl_example/src/lib.rs#L90-L107) but none of them worked which confuses me a bit. Calling `GC.register` seems to be  the solution nokogiri used to fix their problem and I don't understand why ruby would still mess with Values when the GC is running.

**Comment by danielpclark** [comment]
> This PR now just removes the Option around the arguments which makes it easier to pass in vectors. If you are ok with the changes I will squash the commits and update the PR description.

If you make sure to get those 5 other places updated in the docs as well I approve of this.

**Comment by dsander** [comment]
> You would need to at least bump the Rutie version in that example to `0.6.0` and the example won't run until the gem is released. But that example isn't run on CI so it should be fine.

Done, I wasn't sure what do to with that example because I initially wanted to keep it working on master.

**Comment by dsander** [comment]
Sorry for the massive delay, I totally forgot about this PR.

**Comment by danielpclark** [comment]
Thanks. I'll probably get to this next week.

**Pull request merged**
